/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import AliceHelper from 'react-native-alice-helper';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
   
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆AliceHelper example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Pressable
          style={styles.button}
         onPress={()=>{
             AliceHelper.sampleMethod('Testing', 123, (message) => {
              this.setState({
                status: 'native callback received',
                message
              });
            });
        }}>
          <Text style={styles.instructions}>{'Call Native Function'}</Text>
        </Pressable>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  button: {
    backgroundColor: 'pink',
    padding: 10,
    borderRadius: 6,
  }
});
